name: Build
on:
  push:
    branches:
      - 'master'
      - 'feature/*'

env:
  BUILD_IMAGE: ngocnh/php
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 8.2
        uses: docker/build-push-action@v3
        with:
          file: "./Dockerfile"
          push: true
          tags: |
            "${{env.BUILD_IMAGE}}:8.2-fpm-alpine"
            "${{env.BUILD_IMAGE}}:latest"
