jobs:
  name: ci
  on:
    push:
      branches:
        - 'master'
        - 'feature/*'

  jobs:
    login:
      runs-on: ubuntu-latest
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }